export const API_VERSION = 'v1';

export const RATE_LIMITS = {
  STRICT: { max: 10, timeWindow: '1 minute' },
  NORMAL: { max: 100, timeWindow: '15 minutes' },
  LENIENT: { max: 1000, timeWindow: '15 minutes' },
} as const;

export const PASSWORD_RULES = {
  MIN_LENGTH: 8,
  REQUIRE_UPPERCASE: true,
  REQUIRE_LOWERCASE: true,
  REQUIRE_NUMBERS: true,
  REQUIRE_SPECIAL_CHARS: true,
  MAX_FAILED_ATTEMPTS: 5,
  LOCKOUT_DURATION_MINUTES: 15,
} as const;

export const SESSION_CONFIG = {
  COOKIE_NAME: 'session',
  COOKIE_MAX_AGE: 8 * 60 * 60 * 1000, // 8 hours in milliseconds
  REFRESH_THRESHOLD: 30 * 60 * 1000, // 30 minutes in milliseconds
} as const;

export const TOTP_CONFIG = {
  WINDOW: 2,
  PERIOD: 30,
  DIGITS: 6,
  ALGORITHM: 'sha1' as const,
  BACKUP_CODES_COUNT: 10,
  BACKUP_CODE_LENGTH: 8,
} as const;

export const FILE_UPLOAD = {
  MAX_SIZE: 10 * 1024 * 1024, // 10MB
  ALLOWED_TYPES: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf', 'text/plain', 'text/csv'],
  ALLOWED_EXTENSIONS: ['.jpg', '.jpeg', '.png', '.gif', '.pdf', '.txt', '.csv'],
} as const;

export const PAGINATION = {
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
} as const;

export const CACHE_TTL = {
  SHORT: 5 * 60, // 5 minutes
  MEDIUM: 30 * 60, // 30 minutes
  LONG: 24 * 60 * 60, // 24 hours
} as const;

// Error codes
export const ERROR_CODES = {
  // Authentication
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_NOT_VERIFIED: 'ACCOUNT_NOT_VERIFIED',
  
  // 2FA
  INVALID_2FA_CODE: 'INVALID_2FA_CODE',
  TOTP_NOT_ENABLED: 'TOTP_NOT_ENABLED',
  TOTP_ALREADY_ENABLED: 'TOTP_ALREADY_ENABLED',
  INVALID_BACKUP_CODE: 'INVALID_BACKUP_CODE',
  
  // Organizations
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  USER_NOT_MEMBER: 'USER_NOT_MEMBER',
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  OWNER_CANNOT_LEAVE: 'OWNER_CANNOT_LEAVE',
  
  // Invitations
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_ALREADY_ACCEPTED: 'INVITATION_ALREADY_ACCEPTED',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  
  // Resources
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_IN_USE: 'RESOURCE_IN_USE',
  
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  
  // Rate limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  
  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
} as const;

// HTTP Status mappings
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;
